### ISSUE TITLE
Errors on fresh install

### ISSUE THREAD

**Issue by cdcv** [miso-belica/sumy#149]
Did a fresh install on a Mac following instructions given:
```
pip install sumy
pip install git+git://github.com/miso-belica/sumy.git
```

After, running sumy produces errors, eg:

```
>>> sumy lex-rank --length=10 --url=http://en.wikipedia.org/wiki/Automatic_summarization                        
Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/bin/sumy", line 5, in <module>
    from sumy.__main__ import main
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/sumy/__main__.py", line 38, in <module>
    from .nlp.tokenizers import Tokenizer
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/sumy/nlp/tokenizers.py", line 8, in <module>
    import nltk
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.collocations import *
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/nltk/collocations.py", line 35, in <module>
    from nltk.probability import FreqDist
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^
SyntaxError: invalid syntax

>>> python --version                                                                                 
python 2.7.16
```

Help appreciated.  Thanks!

**Comment by miso-belica** [comment]
Hi @cdcv it seems that you have installed a version of the NLTK package that does not support Python 2. You should probably search for the last NLTK package with Python 2 support and downgrade or better [you should upgrade to Python 3](https://docs.python-guide.org/starting/install3/osx/).

Sumy should still support Python 2 but a lot of its dependencies do not so it could be tricky. I plan to drop support for Python 2 too once it will become hard to keep tests in my CI pass.

**Comment by cdcv** [comment]
Thanks miso-belica.  I also have python 3.8.5 installed.  What is the correct command to use sumy w python 3 rather than 2?  Thx again!
