### ISSUE TITLE
Getting error while summarizing URLs.

### ISSUE THREAD

**Issue by dawntcherian** [miso-belica/sumy#81]
When I am trying to pass  any URLs with host-name "techcrunch.com", am getting an error in the code 
`parser = HtmlParser.from_url(url, Tokenizer(settings.LANGUAGE))` 
saying that _SSLError: hostname 'techcrunch.com' doesn't match either of '*.wordpress.com', 'wordpress.com'_

**Comment by miso-belica** [comment]
Hi can you provide the stacktrace of the error? IMHO this is problem in requests library.

**Comment by dawntcherian** [comment]
```
Internal Server Error:
Traceback (most recent call last):
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/user/textsummarizer/bookmarks/views.py", line 88, in post
    parser = HtmlParser.from_url(url, Tokenizer(settings.LANGUAGE))
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/sumy/parsers/html.py", line 35, in from_url
    data = fetch_url(url)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/sumy/utils.py", line 23, in fetch_url
    with closing(requests.get(url, headers=_HTTP_HEADERS)) as response:
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/textsummarizer/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: hostname 'techcrunch.com' doesn't match either of '*.wordpress.com', 'wordpress.com'
```

**Comment by dawntcherian** [comment]
Solved the issue by upgrading requests library to 2.13.0 and installing ndg-httpsclient.
```
pip install --upgrade  requests
pip install ndg-httpsclient
```
