### ISSUE TITLE
some questions about evaluation methods 

### ISSUE THREAD

**Issue by bitterhoneyy** [miso-belica/sumy#95]
When I try `sumy_eval lex-rank reference_summary.txt --url=http://en.wikipedia.org/wiki/Automatic_summarization`, it returns:

```
Traceback (most recent call last):
  File "/home/lizhuyun/.local/bin/sumy_eval", line 11, in <module>
    sys.exit(main())
  File "/home/lizhuyun/.local/lib/python2.7/site-packages/sumy/evaluation/__main__.py", line 160, in main
    summarizer, document, items_count, reference_summary = handle_arguments(args)
  File "/home/lizhuyun/.local/lib/python2.7/site-packages/sumy/evaluation/__main__.py", line 206, in handle_arguments
    with open(args["<reference_summary>"], "rb") as file:
IOError: [Errno 2] No such file or directory: 'reference_summary.txt'
```

Also I can't find  lsa reference_summary.txt and edmundson reference_summary.txt, what should I do?

**Comment by miso-belica** [comment]
Hi, you should create these files. These files contains reference summary. You can create it by some another system or by hand.
