### ISSUE TITLE
Missing stopwords for german language

### ISSUE THREAD

**Issue by workflowsguy** [miso-belica/sumy#96]
When running `sumy` 0.7.0 with the following command line

`sumy lex-rank --lang=de --file="Test-Deutsch.txt"`

the following error is displayed:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sumy/utils.py", line 54, in get_stop_words
    stopwords_data = pkgutil.get_data("sumy", "data/stopwords/%s.txt" % language)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pkgutil.py", line 629, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sumy/data/stopwords/de.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/sumy", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sumy/__main__.py", line 68, in main
    summarizer, parser, items_count = handle_arguments(args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sumy/__main__.py", line 107, in handle_arguments
    stop_words = get_stop_words(language)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sumy/utils.py", line 56, in get_stop_words
    raise LookupError("Stop-words are not available for language %s." % language)
LookupError: Stop-words are not available for language de.


```

**Comment by miso-belica** [comment]
Hi, try `sumy lex-rank --lang=german --file="Test-Deutsch.txt"` and it should work :)

**Comment by workflowsguy** [comment]
Thank you for pointing this out.

It would be great if the language parameters could be given as their ISO 639-1 abbreviations. This would improve interoperability with other tools like e.g. Apache's Tika, which returns the detected language of a file as the above-mentioned language code.

Thanks!

**Comment by c-w** [comment]
I agree that this would be a great feature and increase interoperability with other packages, @workflowsguy.

I've implemented this feature in https://github.com/miso-belica/sumy/pull/106, based on the [pycountry](https://pypi.python.org/pypi/pycountry) package.

After that change gets merged, you'll be able to pass ISO-639 two-letter codes (e.g.,"de") and three-letter codes (e.g., "ger") to specify the language used by sumy, in addition to the existing language-name support (e.g., "german").

**Comment by workflowsguy** [comment]
@c-w Great, Thanks!
